# Generated by Django 5.0 on 2024-02-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_book_model'),
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='categories',
            field=models.ManyToManyField(related_name='category', to='catagories.category'),
        ),
    ]
