# Generated by Django 5.0 on 2024-02-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_purcehased_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='purcehased_history',
            name='balance_after_purchased',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purcehased_history',
            name='purchased_book_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purcehased_history',
            name='purchased_book_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
