# Generated by Django 5.0 on 2024-02-17 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_purcehased_history_balance_after_purchased_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purcehased_history',
            new_name='Purcehase_model',
        ),
    ]
