# Generated by Django 5.0 on 2024-02-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaction',
            new_name='transaction_model',
        ),
    ]
