# Generated by Django 5.0 on 2024-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_transaction_transaction_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_model',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
